/**********************************************/
/* Author: Alzahraa Elsallakh                 */
/* Version: V01                               */
/* Date: 11 Dec 2019                          */
/* Layer: MCAL                                */
/* Component: PORT                            */
/* File Name: PORT_private.h                  */
/**********************************************/

#ifndef PORT_PRIVATE_H
#define PORT_PRIVATE_H

#define Conc(b7,b6,b5,b4,b3,b2,b1,b0) Conc_Help(b7,b6,b5,b4,b3,b2,b1,b0)
#define Conc_Help(b7,b6,b5,b4,b3,b2,b1,b0) 0b##b7##b6##b5##b4##b3##b2##b1##b0

#define PORT_u8_PORTA_DIR Conc(PORT_u8_PORTA_PIN7_DIR,PORT_u8_PORTA_PIN6_DIR,PORT_u8_PORTA_PIN5_DIR,PORT_u8_PORTA_PIN4_DIR,PORT_u8_PORTA_PIN3_DIR,PORT_u8_PORTA_PIN2_DIR,PORT_u8_PORTA_PIN1_DIR,PORT_u8_PORTA_PIN0_DIR)
#define PORT_u8_PORTB_DIR Conc(PORT_u8_PORTB_PIN7_DIR,PORT_u8_PORTB_PIN6_DIR,PORT_u8_PORTB_PIN5_DIR,PORT_u8_PORTB_PIN4_DIR,PORT_u8_PORTB_PIN3_DIR,PORT_u8_PORTB_PIN2_DIR,PORT_u8_PORTB_PIN1_DIR,PORT_u8_PORTB_PIN0_DIR)
#define PORT_u8_PORTC_DIR Conc(PORT_u8_PORTC_PIN7_DIR,PORT_u8_PORTC_PIN6_DIR,PORT_u8_PORTC_PIN5_DIR,PORT_u8_PORTC_PIN4_DIR,PORT_u8_PORTC_PIN3_DIR,PORT_u8_PORTC_PIN2_DIR,PORT_u8_PORTC_PIN1_DIR,PORT_u8_PORTC_PIN0_DIR)
#define PORT_u8_PORTD_DIR Conc(PORT_u8_PORTD_PIN7_DIR,PORT_u8_PORTD_PIN6_DIR,PORT_u8_PORTD_PIN5_DIR,PORT_u8_PORTD_PIN4_DIR,PORT_u8_PORTD_PIN3_DIR,PORT_u8_PORTD_PIN2_DIR,PORT_u8_PORTD_PIN1_DIR,PORT_u8_PORTD_PIN0_DIR)


#define PORT_u8_PORTA_INITIALVALUE Conc(PORT_u8_PORTA_PIN7_INITIALVALUE,PORT_u8_PORTA_PIN6_INITIALVALUE,PORT_u8_PORTA_PIN5_INITIALVALUE,PORT_u8_PORTA_PIN4_INITIALVALUE,PORT_u8_PORTA_PIN3_INITIALVALUE,PORT_u8_PORTA_PIN2_INITIALVALUE,PORT_u8_PORTA_PIN1_INITIALVALUE,PORT_u8_PORTA_PIN0_INITIALVALUE)
#define PORT_u8_PORTB_INITIALVALUE Conc(PORT_u8_PORTB_PIN7_INITIALVALUE,PORT_u8_PORTB_PIN6_INITIALVALUE,PORT_u8_PORTB_PIN5_INITIALVALUE,PORT_u8_PORTB_PIN4_INITIALVALUE,PORT_u8_PORTB_PIN3_INITIALVALUE,PORT_u8_PORTB_PIN2_INITIALVALUE,PORT_u8_PORTB_PIN1_INITIALVALUE,PORT_u8_PORTB_PIN0_INITIALVALUE)
#define PORT_u8_PORTC_INITIALVALUE Conc(PORT_u8_PORTC_PIN7_INITIALVALUE,PORT_u8_PORTC_PIN6_INITIALVALUE,PORT_u8_PORTC_PIN5_INITIALVALUE,PORT_u8_PORTC_PIN4_INITIALVALUE,PORT_u8_PORTC_PIN3_INITIALVALUE,PORT_u8_PORTC_PIN2_INITIALVALUE,PORT_u8_PORTC_PIN1_INITIALVALUE,PORT_u8_PORTC_PIN0_INITIALVALUE)
#define PORT_u8_PORTD_INITIALVALUE Conc(PORT_u8_PORTD_PIN7_INITIALVALUE,PORT_u8_PORTD_PIN6_INITIALVALUE,PORT_u8_PORTD_PIN5_INITIALVALUE,PORT_u8_PORTD_PIN4_INITIALVALUE,PORT_u8_PORTD_PIN3_INITIALVALUE,PORT_u8_PORTD_PIN2_INITIALVALUE,PORT_u8_PORTD_PIN1_INITIALVALUE,PORT_u8_PORTD_PIN0_INITIALVALUE)

#endif